### ISSUE TITLE
Please add support for Queens+

### ISSUE THREAD

**Issue by notandy** [sapcc/secgroup-entanglement-exporter#1]
Hi,

From Neutron version newton on they renamed tenant_id to project_id, see [here](https://github.com/sapcc/neutron/blob/stable/queens-m3/neutron/db/migration/alembic_migrations/versions/newton/contract/7d9d8eeec6ad_rename_tenant_to_project.py), therefor letting the secgroup entanglement export crash with query errors using >=neutron-newton:
```
2018/07/20 14:01:57 INFO: listening on :9102
2018/07/20 14:01:57 FATAL: cannot query Neutron DB: pq: column g.tenant_id does not exist
```

e.g.
https://github.com/sapcc/secgroup-entanglement-exporter/blob/571df15fb379658fbff66e0ffc0cf417f0219978/pkg/core/db.go#L41

best regards

**Comment by majewsky** [comment]
Done. Please deploy https://github.com/sapcc/helm-charts/commit/facf654fee7834b805f8e00aff6258623e945263 and the corresponding changes from cc/secrets.

**Comment by notandy** [comment]
👍
